### ISSUE TITLE
[Bug]: back from edit token icon then crash

### ISSUE THREAD

**Issue by reg-chen** [timokoessler/2FAGuard#16]
### What happened?

back from edit token icon
then app throw exception and crash itself

### Provide the error message / stack trace

Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Wpf.Ui.Controls.NavigationViewActivator.CreateInstance(Type pageType, Object dataContext)
   at Wpf.Ui.Controls.NavigationView.GetPageInstanceFromCache(Type targetPageType)
   at Wpf.Ui.Controls.NavigationView.<>c__DisplayClass114_0.<GetNavigationItemInstance>g__ComputeCachedNavigationInstance|0()
   at Wpf.Ui.Controls.NavigationCache.Remember(Type entryType, NavigationCacheMode cacheMode, Func`1 generate)
   at Wpf.Ui.Controls.NavigationView.GetNavigationItemInstance(INavigationViewItem viewItem)
   at Wpf.Ui.Controls.NavigationView.NavigateInternal(INavigationViewItem viewItem, Object dataContext, Boolean addToNavigationStack, Boolean isBackwardsNavigated)
   at Wpf.Ui.Controls.NavigationView.GoBack()
   at Wpf.Ui.Controls.NavigationView.OnBackButtonClick(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Guard.Program.Main()

### What version of Windows are you using?

Windows 11 22631

### What version of the app are you using?

1.3.0.0 (Microsoft Store)

**Comment by timokoessler** [comment]
Thanks for reporting this bug. Unfortunately, I cannot reproduce it using the same Windows version. Does it happen every time, or only after a specific action?

**Comment by reg-chen** [comment]
follow this operation

https://github.com/timokoessler/2FAGuard/assets/34430957/3e9338b4-8121-4ab2-8302-94becfaede57

will trigger this bug

**Comment by timokoessler** [comment]
Thanks for providing a video 👍
