### ISSUE TITLE
App crashes at startup after 2FAS backup import

### ISSUE THREAD

**Issue by malagem** [timokoessler/2FAGuard#23]
### What happened?

App installed via installer.

After installation, opened app and defined master password. Then imported tokens from a 2FAS Android export. Waited to see if tokens were refreshing, then closed the app.

Reopened the app, and it crashes directly, either after entering the master password, or after signing in via Window Hello.

Will update this ticket after trying to uninstall and reinstall app.

### Provide the error message / stack trace

Object reference not set to an instance of an object.
   at Guard.Views.UIComponents.TokenCard..ctor(TOTPTokenHelper token)
   at Guard.Views.Pages.Home.LoadTokens()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Guard.Program.Main()

### What version of Windows are you using?

Windows 10 19045

### What version of the app are you using?

1.3.1.0 (Desktop Installation)

**Comment by malagem** [comment]
Found the settings in appdata. Deleted the folder. Uninstalled and reinstalled the app again. Defined masted password, signed in using Hello, imported the 2FAS backup and closed. Then restarted the app, and it crashed right after master password or hello like before.

**Comment by malagem** [comment]
Tried to use the app without any master password or hello security. As before, it crashed if reopened after importing the 2FAS backup from android.

**Comment by timokoessler** [comment]
Hi, thanks for opening this issue.
Can you confirm that the app only crashes after importing tokens from 2FAS and not if you add any tokens manually or from another source?

**Comment by malagem** [comment]
I confirm it works when creating a token manually or importing multiple tokens from Google Authenticator with a QR code via the clipboard. It's only after importing a 2FAS backup from Android that it crashes at startup.

**Comment by timokoessler** [comment]
I tried to reproduce this issue by creating multiple encrypted and insecure exports from the latest version of the 2FAS Android app with different tokens and settings. Unfortunately I did not find this bug. Did you used encrypted or unencrypted export? May it be possible that you provide me an 2FAS export or a zip of the app's data folder that does not contain any real tokens, but still has this problem? I would be very grateful.

**Comment by timokoessler** [comment]
Do the logs inside the app data folder contain any additional lines?

**Comment by mikeingz** [comment]
I have exactly the same issue, except that I use the Portable version, on Windows 11.

**Comment by malagem** [comment]
> I tried to reproduce this issue by creating multiple encrypted and insecure exports from the latest version of the 2FAS Android app with different tokens and settings. Unfortunately I did not find this bug. Did you used encrypted or unencrypted export? May it be possible that you provide me an 2FAS export or a zip of the app's data folder that does not contain any real tokens, but still has this problem? I would be very grateful.

I used both encrypted and unencrypted 2FAS Android exports, with the same result. The log is actually empty since I uninstalled the app and wiped the appdata folder several times in order to get it working. I'll see if I can prepare a fake export using another android device.

**Comment by timokoessler** [comment]
That would be very helpful. I tried again by creating multiple exports from the 2FAS Android app with different algorithms, token length etc. but still everything works or it says not supported directly at the import. Don't know why I can not reproduce this.

**Comment by mikeingz** [comment]
The log file I got :
```
2024-07-23 20:18:41.053 +08:00 [ERR] Unhandled Exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Guard.Views.UIComponents.TokenCard..ctor(TOTPTokenHelper token)
   at Guard.Views.Pages.Home.LoadTokens()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Guard.Program.Main()
```

**Comment by timokoessler** [comment]
I created a [portable executable](https://2faguard.app/static-content/2FAGuard-Portable-1.4.0-DEBUG.exe) that should log the exact line of the error in the source code. Maybe you can download and send me the error? Please note that you will not be able to open the same app data folder with the current public app version anymore after using this one.

**Comment by mikeingz** [comment]
> I created a [portable executable](https://2faguard.app/static-content/2FAGuard-Portable-1.4.0-DEBUG.exe) that should log the exact line of the error in the source code. Maybe you can download and send me the error? Please note that you will not be able to open the same app data folder with the current public app version anymore after using this one.

Here is the new log : 
````
2024-07-24 06:55:03.095 +08:00 [ERR] Unhandled Exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Guard.WPF.Views.UIComponents.TokenCard..ctor(TOTPTokenHelper token) in C:\Users\info\Documents\Git\2FAGuard\Guard.WPF\Views\Controls\TokenCard.xaml.cs:line 41
   at Guard.WPF.Views.Pages.Home.LoadTokens() in C:\Users\info\Documents\Git\2FAGuard\Guard.WPF\Views\Pages\Home.xaml.cs:line 78
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Guard.WPF.Program.Main() in C:\Users\info\Documents\Git\2FAGuard\Guard.WPF\Program.cs:line 17
````

**Comment by timokoessler** [comment]
Can also happen with Authenticator Pro import: #27

**Comment by timokoessler** [comment]
Maybe you can try [this portable version](https://2faguard.app/static-content/2FAGuard-Portable-1.4.0-DEBUG-2.exe) and check if it does not crash anymore? If you are able to send me some import data that causes this kind of issue, this would be really helpful, because I still cannot reproduce the bug. Thanks in advance.

**Comment by mikeingz** [comment]
> Maybe you can try [this portable version](https://2faguard.app/static-content/2FAGuard-Portable-1.4.0-DEBUG-2.exe) and check if it does not crash anymore? If you are able to send me some import data that causes this kind of issue, this would be really helpful, because I still cannot reproduce the bug. Thanks in advance.

awesome, it works now, it doesn't crash anymore, great job!!!

**Comment by timokoessler** [comment]
Sadly this does not fix the cause of the issue, only the effects. You should have one or multiple token with "???" as issuer now. Can you check what makes this tokens different from the others?

**Comment by mikeingz** [comment]
Oh right, so here is a screenshot : 

![image](https://github.com/user-attachments/assets/00e9eb6f-3dc2-4679-bc25-706d33d54482)

The first one is actually to connect to the Control Panel of a webhosting server, that looks like that : 

![image](https://github.com/user-attachments/assets/72638a73-8f14-420e-b64d-260d6ef7521f)

**Comment by timokoessler** [comment]
After importing (before restarting) can you see the issuer name of this token instead "???"? If yes, can you send it to me?

**Comment by mikeingz** [comment]
Actually when I use your last portable, but in a new folder (so as a new installation), and if I import the file, and then restart the app, all the names are displayed normally.
The "???" was only visible when using the portable in a previous installation.

Anyway, I don't know if it can help but the datas for the ??? one is : 

````
   {
      "name": "ControlPanel",
      "secret": "xxx",
      "updatedAt": 1710080935488,
      "otp": {
        "label": "xxx",
        "account": "xxx",
        "issuer": "",
        "digits": 6,
        "algorithm": "SHA1",
        "tokenType": "TOTP",
        "source": "Link"
      },
      "order": {
        "position": 1
      },
      "icon": {
        "selected": "Label",
        "label": {
          "text": "CO",
          "backgroundColor": "Red"
        },
        "iconCollection": {
          "id": "xxx"
        }
      }
    },
````

I replaced the sensitive info by xxx

**Comment by timokoessler** [comment]
Found the reason for this bug: The library LiteDB is converting empty strings to null. I will fix this in the evening.

**Comment by timokoessler** [comment]
Version 1.4.0 which should fix this issue has now been released. Please note that it can take some days until the update is available in the Microsoft Store too.
