### ISSUE TITLE
App crashes after importing Authenticator Pro backup

### ISSUE THREAD

**Issue by AccmansRelease** [timokoessler/2FAGuard#27]
### What happened?

The same bug happened previously with the Desktop App (on Windows 11 too)

### Provide the error message / stack trace

Object reference not set to an instance of an object.
   at Guard.Views.UIComponents.TokenCard..ctor(TOTPTokenHelper token)
   at Guard.Views.Pages.Home.LoadTokens()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Guard.Program.Main()

### What version of Windows are you using?

Windows 11 22631

### What version of the app are you using?

1.3.1.0 (Microsoft Store)

**Comment by timokoessler** [comment]
Thanks for reporting, did you import tokens from the 2FAS app?

**Comment by AccmansRelease** [comment]
I don't use the 2FAS app on my phone, but Authenticator Pro and after the first same problem happened, I tried with the Microsoft Store App and imported tokens from Authenticator Pro.

**Comment by timokoessler** [comment]
Does this only happens after restarting the app? If yes, would it be possible that you do the following steps:

1. Download the portable app
2. Run it and import the Authenticator Pro backup
3. Delete all tokens except a few and edit their secret to be something else (random) so that they contain no sensitive data
4. Check if the app is still crashing after a restart
5. Make a Zip of the data folder of the portable app (it's in the same folder as the exe) and send it to me here or via email

That would massively help me to reproduce and fix this issue. Thanks.

**Comment by AccmansRelease** [comment]
Thank you for your help.

 

It happens after a few time of use when I want to open again the app and each time after the first issue.

 

I’m trying now with the portable app and if it’s happen again with this version, I will follow your advices and send you the ZIP folder.

 

Is there a way to delete multiple tokens at once ? Because I have a lot of them and it twill be long to delete them one by one.

 

Thank you again.

 

 

De : Timo Kössler ***@***.***> 
Envoyé : mercredi 24 juillet 2024 16:01
À : timokoessler/2FAGuard ***@***.***>
Cc : Accman_fr ***@***.***>; Author ***@***.***>
Objet : Re: [timokoessler/2FAGuard] App crashes after importing Authenticator Pro backup (Issue #27)

 

Does this only happens after restarting the app? If yes, would it be possible that you do the following steps:

1.	Download the portable app
2.	Run it and import the Authenticator Pro backup
3.	Delete all tokens except a few and edit their secret to be something else (random) so that they contain no sensitive data
4.	Check if the app is still crashing after a restart
5.	Make a Zip of the data folder of the portable app (it's in the same folder as the exe) and send it to me here or via email

That would massively help me to reproduce and fix this issue. Thanks.

**Comment by timokoessler** [comment]
Version 1.4.0 which fixes this issue has now been released. Please note that it can take some days until the update is available in the Microsoft Store too.
